name: http_client
description: 类似 JetBrains HTTP Client 的桌面接口测试工具。
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  web_socket_channel: ^3.0.3
  file_picker: ^8.3.7
  path: ^1.9.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/examples.http
    - assets/default.env.json
